{"name": "test_accept_order_without_order_id_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_accept_order_endpoint.TestAcceptOrder object at 0x00000180D31D35F0>\n\n    def test_accept_order_without_order_id_failed(self):\n        courier_body = Helpers.modify_create_courier_body()\n        ScooterApi.create_courier(courier_body)\n        login_body = courier_body.copy()\n        del login_body['firstName']\n        login_request = ScooterApi.login_courier(login_body)\n        courier_id = login_request.json()[\"id\"]\n    \n        order_body = CreateOrderData.body.copy()\n        order_body[\"color\"] = [\"GREY\"]\n    \n        order_id = ''\n    \n        accept_order_request = ScooterApi.accept_order(order_id, courier_id)\n        check = accept_order_request.url\n>       assert accept_order_request.status_code == 400 and accept_order_request.text == '{\"code\":400,\"message\":\"Недостаточно данных для поиска\"}'\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_accept_order_endpoint.py:60: AssertionError"}, "start": 1726089016184, "stop": 1726089016900, "uuid": "efad3437-e3d1-4002-ac62-0fcbaa3f56c1", "historyId": "74a42b580b91a55a3d85ad628e0dcd51", "testCaseId": "74a42b580b91a55a3d85ad628e0dcd51", "fullName": "tests.test_accept_order_endpoint.TestAcceptOrder#test_accept_order_without_order_id_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order_endpoint"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME"}, {"name": "thread", "value": "17600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order_endpoint"}]}